update

diff --git a/.github/workflows/update-readme.yml b/.github/workflows/update-readme.yml
--- a/.github/workflows/update-readme.yml
+++ b/.github/workflows/update-readme.yml
@@ -2,8 +2,8 @@ name: Update READMEs from Private Repos
 
 on:
   schedule:
-    - cron: '0 0 * * *' # 每小时运行一次
-  workflow_dispatch: # 手动触发
+    - cron: "0 0 * * *"
+  workflow_dispatch:
 
 jobs:
   update-readmes:
@@ -11,17 +11,46 @@ jobs:
 
     steps:
       - name: Checkout Repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       - name: Execute download-docs.ps1
-        run: pwsh download-docs.ps1
+        shell: pwsh
+        run: |
+          . .\download-docs.ps1
 
-      - name: Execute generator-index.ps1
-        run: pwsh generator-index.ps1
+          $Token = ${{ secrets.GITHUB_TOKEN }}
+          $RepoFileName = "RepoNameList.txt"
+          $Proxy = $null
+          $DocsDir = "docs"
+
+          if (-not (Test-Path $RepoFileName)) {
+              Write-Error "File $RepoFileName not found!!!"
+              exit 1
+          }
+          $userName = Get-GitHubUserName -token $Token -proxy $Proxy
+          if (-not $userName) {
+              Write-Error "Can not get GitHub username!!!"
+              exit 1
+          }
+          $repoList = Get-RepoListFromFile -filePath $RepoFileName -userName $userName
+          foreach ($repo in $repoList) {
+              Write-Host "Processing: $repo"
+              Get-GitHubRepoReadmes -token $Token -repoFullName $repo -proxy $Proxy
+              Move-ReadmesToDocs -repoFullName $repo -docsDir $DocsDir
+          }
+
+          Update-MarkdownIndex -DocsDir $DocsDir
 
       - name: Check for changes
+        shell: pwsh
         run: |
           git config --global user.name "github-actions"
           git config --global user.email "actions@github.com"
           git add .
-          git diff --cached --quiet || git commit -m "Update documentation" && git push
+          if git diff --cached --quiet; then
+            echo "No changes to commit."
+          else
+            git commit -m "Update documentation"
+            $token = ${{ secrets.GITHUB_TOKEN }}
+            git push "https://x-access-token:$token@github.com/${{ github.repository }}.git" HEAD:${{ github.ref_name }}
+          fi
